<<<<<<< HEAD
# Generated by Django 3.0 on 2019-01-23 11:46
=======
# Generated by Django 2.1.5 on 2019-01-23 15:47
>>>>>>> f5087d160ff38662faac57e4630010c1650e59bd

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admID', models.IntegerField(default=None)),
                ('adm_time', models.DateTimeField(default=None)),
                ('disch_time', models.DateTimeField(default=None)),
                ('adm_type', models.CharField(choices=[('Elective', (('NB', 'newborn'), ('EL', 'elective'))), ('Non-elective', (('UR', 'urgent'), ('EM', 'emergency')))], default=None, max_length=2)),
                ('inpmor', models.BooleanField(default=None)),
                ('pdismor', models.BooleanField(default=None)),
                ('read', models.BooleanField(default=None)),
                ('los', models.IntegerField(default=0)),
                ('plos', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='DescriptorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemID', models.IntegerField(default=None)),
                ('chart_time', models.DateTimeField(default=None)),
                ('value', models.CharField(default=None, max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('flag', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('kind', models.CharField(max_length=1)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplimicapp.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_num', models.IntegerField(default=None, max_length=1)),
                ('icd_code', models.IntegerField(max_length=6)),
                ('icd_class', models.IntegerField(max_length=2)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplimicapp.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.IntegerField(default=None)),
                ('gender', models.CharField(max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('date_of_birth', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('drug_type', models.CharField(choices=[('M', 'MAIN'), ('A', 'ADDITIVE'), ('B', 'BASE')], default=None, max_length=1)),
                ('drug', models.CharField(default=None, max_length=25)),
                ('drug_name_poe', models.CharField(default=None, max_length=25)),
                ('drug_name_generic', models.CharField(default=None, max_length=25)),
                ('formulary_drug_cd', models.CharField(default=None, max_length=15)),
                ('gsn', models.IntegerField(default=None, max_length=15)),
                ('ndc', models.FloatField(default=None, max_length=25)),
                ('prod_strength', models.CharField(default=None, max_length=25)),
                ('dose_val_rx', models.CharField(default=None, max_length=25)),
                ('dose_unit_rx', models.CharField(default=None, max_length=25)),
                ('form_val_disp', models.CharField(default=None, max_length=25)),
                ('form_unit_disp', models.CharField(default=None, max_length=25)),
                ('route', models.CharField(default=None, max_length=25)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplimicapp.Admission')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplimicapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Sevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplimicapp.Patient'),
        ),
        migrations.AddField(
            model_name='descriptorvalue',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplimicapp.Patient'),
        ),
        migrations.AddField(
            model_name='admission',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplimicapp.Patient'),
        ),
    ]
